In [1]:
import numpy as np
import pandas as pd

# suite des exercice numpy

In [13]:
#exo:20. How to create a 2D array containing random floats between 5 and 10?
ar = np.random.randint(5,10, size=(5,3))+np.random.random((5,3))
ar 

'''
ar = np.random.uniform(5,10, size=(5,3))
'''

array([[8, 7, 9],
       [6, 5, 8],
       [5, 7, 5],
       [6, 7, 8],
       [7, 7, 7]])

In [24]:
#exo 21:How to print only 3 decimal places in python numpy array?
rand_arr=np.random.random([5,3])
np.set_printoptions(precision=3)
rand_arr[:4]
rand_arr
'''
rand_arr = np.random.random([5,3])
np.round(rand_arr,3)
'''

array([[0.248, 0.889, 0.16 ],
       [0.262, 0.367, 0.369],
       [0.969, 0.186, 0.412],
       [0.864, 0.863, 0.558],
       [0.46 , 0.749, 0.314]])

In [34]:
#exos 22:Q. Pretty print rand_arr by suppressing the scientific notation (like 1e10)
np.random.seed(100)
rand_arr = np.random.random([3,3])/1e3
rand_arr[np.set_printoptions(suppress=True, precision=5)]
rand_arr

array([[0.00054, 0.00028, 0.00042],
       [0.00084, 0.     , 0.00012],
       [0.00067, 0.00083, 0.00014]])

In [35]:
#exos:23:Limit the number of items printed in python numpy array a to a maximum of 6 elements.
a = np.arange(15)
a[np.set_printoptions(threshold=3)]

array([[ 0,  1,  2, ..., 12, 13, 14]])

In [49]:
#exos24: Q. Print the full numpy array a without truncating.
a[np.set_printoptions(threshold=6)]
a =np.arange(15)
a[np.set_printoptions(threshold=np.nan)]


In [56]:
#exos25:Import the iris dataset keeping the text intact.
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')
iris[:3]

array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa']], dtype=object)

In [60]:
#exos: Extract the text column species from the 1D iris imported in previous question.
species = np.array([row[4] for row in iris])
species[:5]

array([b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa'], dtype='|S15')

In [68]:
#exos;27 Convert the 1D iris to 2D array iris_2d by omitting the species text field.
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d[:4]
'''
iris_2d = np.array([row.tolist()[:4] for row in iris])
iris[:4]
'''

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2]])

In [84]:
#exos28: Find the mean, median, standard deviation of iris's sepallength (1st column)
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
sepallength = np.array([row[0] for row in iris] , dtype=float)
mu, med, sd = np.mean(sepallength), np.median(sepallength),np.std(sepallength)
mu, med, sd

(5.843333333333334, 5.8, 0.8253012917851409)

In [92]:
#exo29
import sys
'''Create a normalized form of iris's sepallength whose values range 
exactly between 0 and 1 so that the minimum has value 0 and maximum has value 1.
'''
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])
smax, smin = sepallength.max(), sepallength.min()
S = (sepallength - smin)/(smax - smin)
print(S[np.set_printoptions(threshold=sys.maxsize)])

'''
S = (sepallength - Smin)/sepallength.ptp()  # Thanks, David Ojeda!
print(S)

'''

[[0.22222 0.16667 0.11111 0.08333 0.19444 0.30556 0.08333 0.19444 0.02778
  0.16667 0.30556 0.13889 0.13889 0.      0.41667 0.38889 0.30556 0.22222
  0.38889 0.22222 0.30556 0.22222 0.08333 0.22222 0.13889 0.19444 0.19444
  0.25    0.25    0.11111 0.13889 0.30556 0.25    0.33333 0.16667 0.19444
  0.33333 0.16667 0.02778 0.22222 0.19444 0.05556 0.02778 0.19444 0.22222
  0.13889 0.22222 0.08333 0.27778 0.19444 0.75    0.58333 0.72222 0.33333
  0.61111 0.38889 0.55556 0.16667 0.63889 0.25    0.19444 0.44444 0.47222
  0.5     0.36111 0.66667 0.36111 0.41667 0.52778 0.36111 0.44444 0.5
  0.55556 0.5     0.58333 0.63889 0.69444 0.66667 0.47222 0.38889 0.33333
  0.33333 0.41667 0.47222 0.30556 0.47222 0.66667 0.55556 0.36111 0.33333
  0.33333 0.5     0.41667 0.19444 0.36111 0.38889 0.38889 0.52778 0.22222
  0.38889 0.55556 0.41667 0.77778 0.55556 0.61111 0.91667 0.16667 0.83333
  0.66667 0.80556 0.61111 0.58333 0.69444 0.38889 0.41667 0.58333 0.61111
  0.94444 0.94444 0.47222 0.72222 0.36111 

In [94]:
#exos30:Compute the softmax score of sepallength.
def softmax(x):
    '''Compute softmax values for each sets of scores in x'''
    e_x = np.exp(x - np.max(x))
    return e_x / e_x.sum()
scores = sepallength
print(softmax(sepallength))

[0.00222 0.00182 0.00149 0.00135 0.00201 0.003   0.00135 0.00201 0.0011
 0.00182 0.003   0.00164 0.00164 0.001   0.00447 0.00404 0.003   0.00222
 0.00404 0.00222 0.003   0.00222 0.00135 0.00222 0.00164 0.00201 0.00201
 0.00245 0.00245 0.00149 0.00164 0.003   0.00245 0.00331 0.00182 0.00201
 0.00331 0.00182 0.0011  0.00222 0.00201 0.00122 0.0011  0.00201 0.00222
 0.00164 0.00222 0.00135 0.00271 0.00201 0.01484 0.00814 0.01343 0.00331
 0.009   0.00404 0.00737 0.00182 0.00995 0.00245 0.00201 0.00494 0.00546
 0.00603 0.00366 0.01099 0.00366 0.00447 0.00667 0.00366 0.00494 0.00603
 0.00737 0.00603 0.00814 0.00995 0.01215 0.01099 0.00546 0.00404 0.00331
 0.00331 0.00447 0.00546 0.003   0.00546 0.01099 0.00737 0.00366 0.00331
 0.00331 0.00603 0.00447 0.00201 0.00366 0.00404 0.00404 0.00667 0.00222
 0.00404 0.00737 0.00447 0.0164  0.00737 0.009   0.02704 0.00182 0.02003
 0.01099 0.01813 0.009   0.00814 0.01215 0.00404 0.00447 0.00814 0.009
 0.02988 0.02988 0.00546 0.01343 0.00366 0.02988 0.007

In [96]:
#exo31 : Find the 5th and 95th percentile of iris's sepallength
np.percentile(sepallength,5), np.percentile(sepallength,95)


(4.6, 7.254999999999998)